-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtiqqiqEA6OxAHzIJ
/XkbdxxNIoP8zmrfFwsSWWcwlkCgCgYIKoZIzj0DAQehRANCAAQfz/S/Y09IRvuI
YeMN5EH/uDXQEdnuTZrHhWvXobpbMTkJcQcmXanG7N/6jI30z1UYRUHMturIerQx
1Ea15nSk
-----END PRIVATE KEY-----